"""
Pydantic models for Edit Decision List (EDL) generated by AI Director.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional
from pydantic import BaseModel, Field


class EditCut(BaseModel):
    """A single continuous segment selected from the source video."""

    clip_id: int = Field(..., description="1-based sequence index of the cut.")
    start_time: float = Field(..., description="Start timestamp in source video (seconds).")
    end_time: float = Field(..., description="End timestamp in source video (seconds).")
    duration: float = Field(..., description="Duration of this cut in seconds.")
    source_text: Optional[str] = Field(None, description="Spoken transcript covered in this cut.")
    reason: str = Field(..., description="AI Director rationale for including this segment.")


class EditDecisionList(BaseModel):
    """Full Edit Decision List (EDL) saved to jobs/{job_id}/planning/edl.json."""

    job_id: str = Field(..., description="UUID of the job.")
    instruction: Optional[str] = Field(None, description="User instruction used to direct the edit.")
    original_duration: float = Field(..., description="Original video duration in seconds.")
    target_duration: Optional[float] = Field(None, description="Target duration in seconds, if specified.")
    total_planned_duration: float = Field(..., description="Sum of durations of all selected cuts.")
    silence_removed_seconds: float = Field(default=0.0, description="Estimated seconds of silence eliminated.")
    cuts: list[EditCut] = Field(default_factory=list, description="Ordered cuts to be rendered.")
    summary: str = Field(..., description="Editorial summary from the AI Director.")
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO timestamp when the EDL was generated.",
    )
